---
title: Rochester Flower Company
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Craft cannabis cultivation in Rochester, NY
url: https://rochesterflowercompany.com
baseurl: 
future: true
markdown: kramdown
permalink: "/blog/:year/:month/:day/:title/"
paginate: 6
paginate_path: "/plants/page/:num/"
exclude:
- README.md
- LICENSE
- CNAME
- ".gitignore"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-seo-tag
category_names:
  grow-tips: Grow Tips
  winter-2025: Winter 2025
  spring-2025: Spring 2025
  summer-2025: Summer 2025
  fall-2025: Fall 2025
  harvest: Harvest
  genetics: Genetics
  updates: Updates
